In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [5]:
print(y.grad_fn)

In [7]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [10]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.requires_grad)
print(b.grad_fn)

False
True
True


In [11]:
out.backward()

In [12]:
print(x.grad)  #verify by differentiation

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [21]:
x = torch.randn(3, requires_grad = True)
y = x*2
print(y)
print(y.data.norm())
while y.data.norm() < 1000:
    print(y.data.norm())
    y = y * 2
print(y)

tensor([-1.3258,  0.2564,  0.2624], grad_fn=<MulBackward>)
tensor(1.3756)
tensor(1.3756)
tensor(2.7513)
tensor(5.5026)
tensor(11.0052)
tensor(22.0104)
tensor(44.0207)
tensor(88.0415)
tensor(176.0830)
tensor(352.1660)
tensor(704.3319)
tensor([-1357.6477,   262.5146,   268.7236], grad_fn=<MulBackward>)


In [22]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([ 204.8000, 2048.0000,    0.2048])


In [25]:
#stop autograd
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
