In [1]:
from __future__ import print_function
import torch

In [2]:
#uninitialised 5x3 matrix
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 3.0922e-29],
        [1.5846e+29,        nan, 1.4013e-45],
        [6.6824e-07, 1.6782e-07, 5.2893e+22],
        [1.6893e-07, 5.2708e-08, 3.2774e-09],
        [5.4126e+22, 6.5926e-10, 8.5033e-25]])


In [4]:
#Randomly initialied matrix
x = torch.rand(5,3)
print(x)

tensor([[0.1346, 0.5887, 0.6450],
        [0.6280, 0.6237, 0.6503],
        [0.3671, 0.1162, 0.1260],
        [0.0933, 0.4614, 0.4183],
        [0.3418, 0.4884, 0.9265]])


In [5]:
#Matrix of zeros and of type long
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
#Tensor directly from data
x = torch.tensor([5, 3.3])
print(x)

tensor([5.0000, 3.3000])


tensor([5.0000, 3.3000])

In [11]:
#Tensor from an existing tensor
x = x.new_ones(5,3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float) #Overrude dtype, but same size
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2939,  0.4656, -0.8098],
        [-0.2209,  0.8153,  1.5218],
        [-0.0003,  0.1084, -1.8232],
        [-0.5533,  0.0451,  0.4055],
        [ 0.4700,  0.3225,  0.0507]])


In [12]:
# print size
print(x.size())

torch.Size([5, 3])


In [15]:
#addition
y = torch.rand(5,3)
print(y)
print(x + y) #One method
print(torch.add(x,y)) #Another method

tensor([[0.9638, 0.8111, 0.3384],
        [0.7651, 0.8582, 0.5496],
        [0.8026, 0.3139, 0.3949],
        [0.4844, 0.9164, 0.7646],
        [0.9233, 0.1122, 0.4591]])
tensor([[ 0.6699,  1.2766, -0.4714],
        [ 0.5442,  1.6735,  2.0714],
        [ 0.8023,  0.4223, -1.4283],
        [-0.0689,  0.9616,  1.1701],
        [ 1.3933,  0.4348,  0.5098]])
tensor([[ 0.6699,  1.2766, -0.4714],
        [ 0.5442,  1.6735,  2.0714],
        [ 0.8023,  0.4223, -1.4283],
        [-0.0689,  0.9616,  1.1701],
        [ 1.3933,  0.4348,  0.5098]])


In [17]:
#Output tensor as argument
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6699,  1.2766, -0.4714],
        [ 0.5442,  1.6735,  2.0714],
        [ 0.8023,  0.4223, -1.4283],
        [-0.0689,  0.9616,  1.1701],
        [ 1.3933,  0.4348,  0.5098]])


In [32]:
#in place addition
y.add_(x)  #any operation with _ prefix mutates the tensor

tensor([[-0.5059,  3.1389, -3.7106],
        [-0.3394,  4.9347,  8.1585],
        [ 0.8013,  0.8559, -8.7211],
        [-2.2822,  1.1421,  2.7922],
        [ 3.2734,  1.7249,  0.7124]])

In [35]:
#indexing same as numpy
print(x)
print(x[:,2])

tensor([[-0.2939,  0.4656, -0.8098],
        [-0.2209,  0.8153,  1.5218],
        [-0.0003,  0.1084, -1.8232],
        [-0.5533,  0.0451,  0.4055],
        [ 0.4700,  0.3225,  0.0507]])
tensor([-0.8098,  1.5218, -1.8232,  0.4055,  0.0507])


In [41]:
#reshape tensor
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [43]:
print(x, "\n", y, "\n", z)

tensor([[ 0.4461, -1.0740,  0.9035,  0.3012],
        [ 0.2425, -0.9464, -0.5345,  1.9026],
        [-0.3748, -1.1119, -0.8004, -0.7511],
        [ 1.9160,  1.0785, -0.5934, -0.0134]]) 
 tensor([ 0.4461, -1.0740,  0.9035,  0.3012,  0.2425, -0.9464, -0.5345,  1.9026,
        -0.3748, -1.1119, -0.8004, -0.7511,  1.9160,  1.0785, -0.5934, -0.0134]) 
 tensor([[ 0.4461, -1.0740,  0.9035,  0.3012,  0.2425, -0.9464, -0.5345,  1.9026],
        [-0.3748, -1.1119, -0.8004, -0.7511,  1.9160,  1.0785, -0.5934, -0.0134]])


In [46]:
# get value from one element tensor
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6241])
-0.6241282224655151


In [49]:
#total elements in tensor
torch.numel(y)

16

In [57]:
#1 D tensor with interval
print(torch.arange(5))
print(torch.arange(1,4))
print(torch.arange(1,4,0.5))
print(torch.range(1,4))  #deprecated

tensor([0, 1, 2, 3, 4])
tensor([1, 2, 3])
tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000])
tensor([1., 2., 3., 4.])


/Users/jishadav/.virtualenvs/car/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """


In [68]:
#concatenation
x = torch.randn(2,3)
print(x)
print(torch.cat((x, x, x)))
print(torch.cat((x, x, x), 0))
print(torch.cat((x, x, x), 1))

tensor([[ 0.6682, -0.5404, -0.1478],
        [-0.3429, -0.1833,  0.7666]])
tensor([[ 0.6682, -0.5404, -0.1478],
        [-0.3429, -0.1833,  0.7666],
        [ 0.6682, -0.5404, -0.1478],
        [-0.3429, -0.1833,  0.7666],
        [ 0.6682, -0.5404, -0.1478],
        [-0.3429, -0.1833,  0.7666]])
tensor([[ 0.6682, -0.5404, -0.1478],
        [-0.3429, -0.1833,  0.7666],
        [ 0.6682, -0.5404, -0.1478],
        [-0.3429, -0.1833,  0.7666],
        [ 0.6682, -0.5404, -0.1478],
        [-0.3429, -0.1833,  0.7666]])
tensor([[ 0.6682, -0.5404, -0.1478,  0.6682, -0.5404, -0.1478,  0.6682, -0.5404,
         -0.1478],
        [-0.3429, -0.1833,  0.7666, -0.3429, -0.1833,  0.7666, -0.3429, -0.1833,
          0.7666]])


In [80]:
#chunking
print(torch.chunk(x, 2, dim=0))
print(torch.chunk(x, 2, dim=1))

(tensor([[ 0.6682, -0.5404, -0.1478]]), tensor([[-0.3429, -0.1833,  0.7666]]))
(tensor([[ 0.6682, -0.5404],
        [-0.3429, -0.1833]]), tensor([[-0.1478],
        [ 0.7666]]))


In [94]:
#gathering
x = torch.randn(2,3)
print(x)
torch.gather(x, 1, torch.tensor([[0,0],[1,1]]))

tensor([[-0.4280, -1.1769, -1.5593],
        [ 1.1285,  0.5774, -0.1115]])


tensor([[-0.4280, -0.4280],
        [ 0.5774,  0.5774]])

In [95]:
# masked_select
x = torch.randn(3,4)
print(x)
mask = x.ge(0.5)
print(mask)
torch.masked_select(x, mask)

tensor([[ 0.0841,  1.3465, -1.3907,  1.4734],
        [ 0.7182,  1.8542,  0.8492,  0.8741],
        [ 0.7794,  1.1642,  1.4259,  1.3501]])
tensor([[0, 1, 0, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)


tensor([1.3465, 1.4734, 0.7182, 1.8542, 0.8492, 0.8741, 0.7794, 1.1642, 1.4259,
        1.3501])

In [98]:
#return indices of all nonzero elements
print(torch.nonzero(torch.tensor([1, 1, 1, 0, 1])))
print(torch.nonzero(torch.tensor([[1.6, 0.0, 1.0, 0.0],
                                [0.0, 0.4, 0.0, 0.0],
                                [1.0, 0.0, 1.2, 0.0],
                                [0.0, 2, 0.0,-0.4]])))

tensor([[0],
        [1],
        [2],
        [4]])
tensor([[0, 0],
        [0, 2],
        [1, 1],
        [2, 0],
        [2, 2],
        [3, 1],
        [3, 3]])


In [99]:
# reshaping
a = torch.arange(4)
torch.reshape(a,(2,2))

tensor([[0, 1],
        [2, 3]])

In [104]:
#squeezing
x = torch.zeros(2, 1, 2, 1, 2)
print(x)
torch.squeeze(x)

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])


tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [109]:
# Where  -> return elements from either x or y depending on condition
x = torch.randn(3,2)
y = torch.ones(3,2)
print(x)
print(y)
torch.where(x>1, x , y)

tensor([[ 0.3825,  1.8947],
        [-1.4522,  0.3021],
        [ 0.0917,  1.2722]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


tensor([[1.0000, 1.8947],
        [1.0000, 1.0000],
        [1.0000, 1.2722]])

In [112]:
#serialization
x  = torch.tensor([0,1, 2, 3])
torch.save(x, 'tensor.pt')  #save to file

In [116]:
torch.load('tensor.pt') #loading save file
torch.load('tensor.pt', map_location=torch.device('cpu')) # --> load to cpu

tensor([0, 1, 2, 3])

In [117]:
#Get threads
torch.get_num_threads()

1

In [119]:
#argmax
a = torch.randn(4, 4)
print(a)
print(torch.argmax(a))
print(torch.argmax(a, dim=1))

tensor([[ 0.6914, -0.3360, -0.4604,  0.5171],
        [ 0.6111,  0.7812,  0.3836,  0.0660],
        [-0.7420, -1.3848,  0.2801,  0.1430],
        [ 0.3961, -0.5558,  0.4314, -1.0765]])
tensor(5)
tensor([0, 1, 2, 2])


In [122]:
#Sorting
x = torch.randn(3, 4)
print(x)
print(torch.sort(x))
print(torch.sort(x, 0))

tensor([[ 0.3800, -1.5606, -0.0135, -0.2978],
        [-1.2256,  0.1873, -0.6492, -2.0008],
        [ 0.8812, -0.3936, -1.2606,  2.0059]])
(tensor([[-1.5606, -0.2978, -0.0135,  0.3800],
        [-2.0008, -1.2256, -0.6492,  0.1873],
        [-1.2606, -0.3936,  0.8812,  2.0059]]), tensor([[1, 3, 2, 0],
        [3, 0, 2, 1],
        [2, 1, 0, 3]]))
(tensor([[-1.2256, -1.5606, -1.2606, -2.0008],
        [ 0.3800, -0.3936, -0.6492, -0.2978],
        [ 0.8812,  0.1873, -0.0135,  2.0059]]), tensor([[1, 0, 2, 1],
        [0, 2, 1, 0],
        [2, 1, 0, 2]]))


In [128]:
# Torch tensor to numpy array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
c = torch.from_numpy(b)
print(c)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


In [129]:
# move tensors onto any device
x.to(device)

NameError: name 'device' is not defined